### ISSUE TITLE
Clean up mobile issues

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#10]
On mobile there are multiple small issues on the details page

**Comment by josepetew** [comment]
Which ones?

**Comment by josepetew** [comment]
https://github.com/The-Grid-Data/Explorer/commit/ff24e0c6bed1a0fd187c48faa43e07bea38c988b updated a couple of issues here. let me know if the issue you meant is fixed

**Comment by josepetew** [comment]
fixed by https://github.com/The-Grid-Data/Explorer/commit/67b95dd249e232820507303b324d0c6b78aeed87
