### ISSUE TITLE
Product -> Supports is incorrect 

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#11]
![CleanShot 2024-06-15 at 18 30 26](https://github.com/The-Grid-Data/Explorer/assets/155550137/df828639-0006-4da7-b483-c2b6cc676270)

**Comment by JJKnegtel** [comment]
Should be: 

      supportsProducts {
        supports {
          name
        }
      }

**Comment by josepetew** [comment]
fixed by https://github.com/The-Grid-Data/Explorer/commit/ff24e0c6bed1a0fd187c48faa43e07bea38c988b
