### ISSUE TITLE
Add 'claim profile' in the top 

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#14]
Link TBD

**Comment by josepetew** [comment]
Where in the top? Not in the design yet.
![Screenshot 2024-06-16 at 23 22 37](https://github.com/The-Grid-Data/Explorer/assets/2585619/81c6b2ed-d390-4313-bc69-2f62d4013b9f)

**Comment by josepetew** [comment]
fixed by https://github.com/The-Grid-Data/Explorer/commit/7c74d26423b3c9a5a5f08359ff2fafda2120aa60
