### ISSUE TITLE
Discord link is inccorect (swap discord <> Telegram icons)

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#15]
![CleanShot 2024-06-16 at 16 12 15](https://github.com/The-Grid-Data/Explorer/assets/155550137/8f1f9cb9-28be-47cd-95bb-490a19d9f9d2)

**Comment by josepetew** [comment]
fixed by https://github.com/The-Grid-Data/Explorer/commit/ff24e0c6bed1a0fd187c48faa43e07bea38c988b
