### ISSUE TITLE
Update border around logo to be the same as the box

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#16]
![CleanShot 2024-06-16 at 18 10 40](https://github.com/The-Grid-Data/Explorer/assets/155550137/008af1b3-24ce-4584-9156-229fdf49c358)

**Comment by josepetew** [comment]
closed by https://github.com/The-Grid-Data/Explorer/commit/d02f6a26d4dbf70c94bd773580b09c3063e4706c
