### ISSUE TITLE
Update from TGS5 to TGS7 (Into Beta)

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#58]
TO DO 

Key notes:
- Add URLs to products + Assets

**Comment by hugomoura10** [comment]
[json_migrations_profileInfos_5_7.json](https://github.com/user-attachments/files/17919745/json_migrations_profileInfos_5_7.json)

Raw json with tgs7 updates

**Comment by JJKnegtel** [comment]
Has been completed
