### ISSUE TITLE
Update profile slug from an ID to a name

### ISSUE THREAD

**Issue by JJKnegtel** [The-Grid-Data/Explorer#8]
@sergrid we may need to create a new data point which is a unique slug. WDYT?

**Comment by josepetew** [comment]
Indeed the FE needs a unique slug to query the profile by that slug

**Comment by JJKnegtel** [comment]
Update: We are adding slug

**Comment by josepetew** [comment]
fixed by https://github.com/The-Grid-Data/Explorer/commit/858631e93437820bc8b8a0c6e190fe5f54c4705c
